services:
  api:
    build: .
    container_name: short-clicks-api
    ports:
      - '8000:8000'
    env_file:
      - .env
      # 2. Override the specific ones that change in Docker
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: short-clicks-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: short-clicks-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
networks:
  app-network:
    driver: bridge
